version: 2

run:
  timeout: 5m
  tests: true

linters:
  disable-all: true
  enable:
    # Core linters
    - errcheck      # Check for unchecked errors
    - govet         # Vet examines Go source code
    - staticcheck   # Static analysis (includes unused check)
    - ineffassign   # Detect ineffectual assignments

linters-settings:
  govet:
    enable-all: true
    disable:
      - shadow  # Too many false positives

  staticcheck:
    checks: ["all"]

  errcheck:
    check-blank: false
    check-type-assertions: false

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude-rules:
    # Exclude some linters from running on test files
    - path: _test\.go
      linters:
        - errcheck

    # Exclude known issues
    - linters:
        - staticcheck
      text: "SA1019:" # Ignore deprecation warnings

  exclude-dirs:
    - vendor

output:
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
