version: '3'

vars:
  TAILWIND_VERSION: v3.4.17
  BIN_DIR: bin
  CSS_INPUT: ui/styles/input.css
  CSS_OUTPUT: ui/static/output.css
  VERSION:
    sh: |
      if git describe --tags --exact-match HEAD 2>/dev/null; then
        :
      else
        BASE_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "dev")
        BRANCH=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "")
        if [ -n "$BRANCH" ] && [ "$BRANCH" != "HEAD" ]; then
          CLEAN_BRANCH=$(echo "$BRANCH" | sed 's/[^a-zA-Z0-9._-]/-/g')
          echo "${BASE_TAG}-${CLEAN_BRANCH}"
        else
          git describe --tags --always 2>/dev/null || echo "dev"
        fi
      fi
  LDFLAGS: "-X 'github.com/b0bbywan/go-odio-api/config.AppVersion={{.VERSION}}'"

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  install-tailwind:
    desc: Download Tailwind CLI (only on supported architectures)
    vars:
      TAILWIND_BINARY:
        sh: |
          case "$(uname -m)" in
            x86_64)  echo "tailwindcss-linux-x64" ;;
            aarch64|arm64) echo "tailwindcss-linux-arm64" ;;
            armv7l)  echo "tailwindcss-linux-armv7" ;;
            *)       echo "" ;;
          esac
    cmds:
      - |
        if [ -z "{{.TAILWIND_BINARY}}" ]; then
          echo "⚠️  Tailwind CLI not available for $(uname -m), will use CDN"
          exit 0
        fi
        mkdir -p {{.BIN_DIR}}
        curl -sL https://github.com/tailwindlabs/tailwindcss/releases/download/{{.TAILWIND_VERSION}}/{{.TAILWIND_BINARY}} -o {{.BIN_DIR}}/tailwindcss
        chmod +x {{.BIN_DIR}}/tailwindcss
        echo "✓ Tailwind CLI installed to {{.BIN_DIR}}/tailwindcss"
    status:
      - test -f {{.BIN_DIR}}/tailwindcss

  css-local:
    desc: Build CSS locally (if Tailwind CLI available)
    deps: [install-tailwind]
    method: checksum
    sources:
      - "{{.CSS_INPUT}}"
      - ui/templates/**/*.gohtml
      - tailwind.config.js
    generates:
      - "{{.CSS_OUTPUT}}"
    cmds:
      - |
        if [ ! -x {{.BIN_DIR}}/tailwindcss ]; then
          echo "⚠️  Tailwind CLI not available, skipping local build"
          exit 0
        fi
        {{.BIN_DIR}}/tailwindcss -i {{.CSS_INPUT}} -o {{.CSS_OUTPUT}} --minify
        echo "✓ CSS compiled to {{.CSS_OUTPUT}}"

  css-download:
    desc: Download pre-built CSS from CDN (only if Tailwind CLI unavailable)
    vars:
      COMMIT_HASH:
        sh: git rev-parse --short HEAD
      BRANCH:
        sh: git rev-parse --abbrev-ref HEAD
      CSS_URL_COMMIT: https://bobbywan.me/odio-css/{{.BRANCH}}/{{.COMMIT_HASH}}.css
      CSS_URL_LATEST: https://bobbywan.me/odio-css/{{.BRANCH}}/latest.css
    status:
      - test -x {{.BIN_DIR}}/tailwindcss  # Skip if we can compile locally
    cmds:
      - mkdir -p ui/static
      - |
        # Essayer d'abord le commit spécifique
        echo "📥 Downloading CSS for {{.BRANCH}}/{{.COMMIT_HASH}}..."
        if curl -fsSL -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36" {{.CSS_URL_COMMIT}} -o {{.CSS_OUTPUT}}; then
          echo "✅ CSS downloaded from {{.BRANCH}}/{{.COMMIT_HASH}}.css"
          exit 0
        fi

        # Fallback sur latest.css
        echo "⚠️  Commit-specific CSS not found, trying latest..."
        if curl -fsSL -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36" {{.CSS_URL_LATEST}} -o {{.CSS_OUTPUT}}; then
          echo "✅ CSS downloaded from {{.BRANCH}}/latest.css"
        else
          echo "❌ No CSS found for {{.BRANCH}}"
          echo "💡 CI may not have run yet on this branch"
          exit 1
        fi

  css:
    desc: Ensure CSS is available (generate locally or download from CDN)
    cmds:
      - task: css-local
      - task: css-download

  css:watch:
    desc: Watch and recompile CSS on changes (development)
    deps: [install-tailwind]
    cmds:
      - |
        if [ ! -x {{.BIN_DIR}}/tailwindcss ]; then
          echo "❌ Tailwind CLI required for watch mode"
          exit 1
        fi
        {{.BIN_DIR}}/tailwindcss -i {{.CSS_INPUT}} -o {{.CSS_OUTPUT}} --watch

  build:
    desc: Build the application (includes CSS compilation)
    deps: [css]
    cmds:
      - go build -ldflags="{{.LDFLAGS}}" -o {{.BIN_DIR}}/odio-api .
      - echo "✓ Built {{.BIN_DIR}}/odio-api (version {{.VERSION}})"
    sources:
      - "**/*.go"
      - go.mod
      - go.sum
      - ui/templates/**/*.gohtml
      - ui/static/**
    generates:
      - "{{.BIN_DIR}}/odio-api"

  test:
    desc: Run all tests
    deps: [css]
    cmds:
      - go test ./...

  test:verbose:
    desc: Run all tests with verbose output
    deps: [css]
    cmds:
      - go test -v ./...

  test:coverage:
    desc: Run tests with coverage report
    deps: [css]
    cmds:
      - go test -v -race -coverprofile=coverage.out -covermode=atomic ./...
      - go tool cover -func=coverage.out

  test:ui:
    desc: Run UI tests only
    deps: [css]
    cmds:
      - go test -v ./ui/...

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf {{.BIN_DIR}}/odio-api
      - rm -f {{.CSS_OUTPUT}}
      - echo "✓ Cleaned build artifacts"

  clean:all:
    desc: Clean all generated files (including Tailwind CLI)
    cmds:
      - rm -rf {{.BIN_DIR}}
      - rm -f {{.CSS_OUTPUT}}
      - echo "✓ Cleaned all generated files"

  dev:
    desc: Start development mode (CSS watch + manual server restart)
    deps: [css]
    cmds:
      - echo "Starting CSS watch mode..."
      - echo "Run 'go run .' in another terminal to start the server"
      - task: css:watch
