version: '3'

vars:
  TAILWIND_VERSION: v3.4.17
  BIN_DIR: bin
  CSS_INPUT: ui/styles/input.css
  CSS_OUTPUT: ui/static/output.css

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  install-tailwind:
    desc: Download Tailwind CLI (only on supported architectures)
    vars:
      TAILWIND_BINARY:
        sh: |
          case "$(uname -m)" in
            x86_64)  echo "tailwindcss-linux-x64" ;;
            aarch64|arm64) echo "tailwindcss-linux-arm64" ;;
            armv7l)  echo "tailwindcss-linux-armv7" ;;
            *)       echo "" ;;
          esac
    cmds:
      - |
        if [ -z "{{.TAILWIND_BINARY}}" ]; then
          echo "⚠️  Tailwind CLI not available for $(uname -m), will use CDN"
          exit 0
        fi
        mkdir -p {{.BIN_DIR}}
        curl -sL https://github.com/tailwindlabs/tailwindcss/releases/download/{{.TAILWIND_VERSION}}/{{.TAILWIND_BINARY}} -o {{.BIN_DIR}}/tailwindcss
        chmod +x {{.BIN_DIR}}/tailwindcss
        echo "✓ Tailwind CLI installed to {{.BIN_DIR}}/tailwindcss"
    status:
      - test -f {{.BIN_DIR}}/tailwindcss

  css-local:
    desc: Build CSS locally (if Tailwind CLI available)
    deps: [install-tailwind]
    sources:
      - "{{.CSS_INPUT}}"
      - ui/templates/**/*.gohtml
      - tailwind.config.js
    generates:
      - "{{.CSS_OUTPUT}}"
    cmds:
      - |
        if [ ! -x {{.BIN_DIR}}/tailwindcss ]; then
          echo "⚠️  Tailwind CLI not available, skipping local build"
          exit 0
        fi
        {{.BIN_DIR}}/tailwindcss -i {{.CSS_INPUT}} -o {{.CSS_OUTPUT}} --minify
        echo "✓ CSS compiled to {{.CSS_OUTPUT}}"

  css-download:
    desc: Download pre-built CSS from CDN
    vars:
      COMMIT_HASH:
        sh: git rev-parse --short HEAD
      BRANCH:
        sh: git rev-parse --abbrev-ref HEAD
      CSS_URL: https://bobbywan.me/odio-css/{{.BRANCH}}/{{.COMMIT_HASH}}.css
    cmds:
      - |
        if [ -f {{.CSS_OUTPUT}} ]; then
          echo "ℹ️  CSS already exists, skipping download"
          exit 0
        fi
        mkdir -p ui/static
        echo "📥 Downloading CSS for {{.BRANCH}}/{{.COMMIT_HASH}}..."
        if curl -fsSL {{.CSS_URL}} -o {{.CSS_OUTPUT}}; then
          echo "✅ CSS downloaded from {{.BRANCH}}/{{.COMMIT_HASH}}.css"
        else
          echo "❌ CSS not found for {{.BRANCH}}/{{.COMMIT_HASH}}"
          echo "💡 Run CI first or build on a platform with Tailwind CLI"
          exit 1
        fi

  css:
    desc: Ensure CSS is available (generate locally or download from CDN)
    cmds:
      - task: css-local
      - task: css-download

  css:watch:
    desc: Watch and recompile CSS on changes (development)
    deps: [install-tailwind]
    cmds:
      - |
        if [ ! -x {{.BIN_DIR}}/tailwindcss ]; then
          echo "❌ Tailwind CLI required for watch mode"
          exit 1
        fi
        {{.BIN_DIR}}/tailwindcss -i {{.CSS_INPUT}} -o {{.CSS_OUTPUT}} --watch

  build:
    desc: Build the application (includes CSS compilation)
    deps: [css]
    cmds:
      - go build -o {{.BIN_DIR}}/go-odio-api
      - echo "✓ Built to {{.BIN_DIR}}/go-odio-api"
    sources:
      - "**/*.go"
      - go.mod
      - go.sum
    generates:
      - "{{.BIN_DIR}}/go-odio-api"

  test:
    desc: Run all tests
    deps: [css]
    cmds:
      - go test ./...

  test:verbose:
    desc: Run all tests with verbose output
    deps: [css]
    cmds:
      - go test -v ./...

  test:coverage:
    desc: Run tests with coverage report
    deps: [css]
    cmds:
      - go test -v -race -coverprofile=coverage.out -covermode=atomic ./...
      - go tool cover -func=coverage.out

  test:ui:
    desc: Run UI tests only
    deps: [css]
    cmds:
      - go test -v ./ui/...

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf {{.BIN_DIR}}/go-odio-api
      - rm -f {{.CSS_OUTPUT}}
      - echo "✓ Cleaned build artifacts"

  clean:all:
    desc: Clean all generated files (including Tailwind CLI)
    cmds:
      - rm -rf {{.BIN_DIR}}
      - rm -f {{.CSS_OUTPUT}}
      - echo "✓ Cleaned all generated files"

  dev:
    desc: Start development mode (CSS watch + manual server restart)
    deps: [css]
    cmds:
      - echo "Starting CSS watch mode..."
      - echo "Run 'go run .' in another terminal to start the server"
      - task: css:watch
