version: '3'

vars:
  TAILWIND_VERSION: v3.4.17
  BIN_DIR: bin
  CSS_INPUT: ui/styles/input.css
  CSS_OUTPUT: ui/static/output.css
  VERSION:
    sh: |
      if git describe --tags --exact-match HEAD 2>/dev/null; then
        :
      else
        BASE_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "dev")
        BRANCH=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "")
        if [ -n "$BRANCH" ] && [ "$BRANCH" != "HEAD" ]; then
          CLEAN_BRANCH=$(echo "$BRANCH" | sed 's/[^a-zA-Z0-9._-]/-/g')
          echo "${BASE_TAG}-${CLEAN_BRANCH}"
        else
          git describe --tags --always 2>/dev/null || echo "dev"
        fi
      fi
  LDFLAGS: "-X 'github.com/b0bbywan/go-odio-api/config.AppVersion={{.VERSION}}'"

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  install-tailwind:
    desc: Download Tailwind CLI (only on supported architectures)
    run: once
    vars:
      TAILWIND_BINARY:
        sh: |
          case "$(uname -m)" in
            x86_64)  echo "tailwindcss-linux-x64" ;;
            aarch64|arm64) echo "tailwindcss-linux-arm64" ;;
            armv7l)  echo "tailwindcss-linux-armv7" ;;
            *)       echo "" ;;
          esac
    cmds:
      - |
        if [ -z "{{.TAILWIND_BINARY}}" ]; then
          echo "⚠️  Tailwind CLI not available for $(uname -m), will use CDN"
          exit 0
        fi
        mkdir -p {{.BIN_DIR}}
        curl -sL https://github.com/tailwindlabs/tailwindcss/releases/download/{{.TAILWIND_VERSION}}/{{.TAILWIND_BINARY}} -o {{.BIN_DIR}}/tailwindcss
        chmod +x {{.BIN_DIR}}/tailwindcss
        echo "✓ Tailwind CLI installed to {{.BIN_DIR}}/tailwindcss"
    status:
      - test -f {{.BIN_DIR}}/tailwindcss

  css-local:
    desc: Build CSS locally (if Tailwind CLI available)
    deps: [install-tailwind]
    method: checksum
    sources:
      - "{{.CSS_INPUT}}"
      - ui/templates/**/*.gohtml
      - tailwind.config.js
    generates:
      - "{{.CSS_OUTPUT}}"
    cmds:
      - |
        if [ ! -x {{.BIN_DIR}}/tailwindcss ]; then
          echo "⚠️  Tailwind CLI not available, skipping local build"
          exit 0
        fi
        {{.BIN_DIR}}/tailwindcss -i {{.CSS_INPUT}} -o {{.CSS_OUTPUT}} --minify
        echo "✓ CSS compiled to {{.CSS_OUTPUT}}"

  css-download:
    desc: Download pre-built CSS from CDN (only if Tailwind CLI unavailable)
    vars:
      COMMIT_HASH:
        sh: git rev-parse --short HEAD
      BRANCH:
        sh: git rev-parse --abbrev-ref HEAD
      CSS_URL_COMMIT: https://bobbywan.me/odio-css/{{.BRANCH}}/{{.COMMIT_HASH}}.css
      CSS_URL_LATEST: https://bobbywan.me/odio-css/{{.BRANCH}}/latest.css
    status:
      - test -x {{.BIN_DIR}}/tailwindcss  # Skip if we can compile locally
    cmds:
      - mkdir -p ui/static
      - |
        # Essayer d'abord le commit spécifique
        echo "📥 Downloading CSS for {{.BRANCH}}/{{.COMMIT_HASH}}..."
        if curl -fsSL -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36" {{.CSS_URL_COMMIT}} -o {{.CSS_OUTPUT}}; then
          echo "✅ CSS downloaded from {{.BRANCH}}/{{.COMMIT_HASH}}.css"
          exit 0
        fi

        # Fallback sur latest.css
        echo "⚠️  Commit-specific CSS not found, trying latest..."
        if curl -fsSL -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36" {{.CSS_URL_LATEST}} -o {{.CSS_OUTPUT}}; then
          echo "✅ CSS downloaded from {{.BRANCH}}/latest.css"
        else
          echo "❌ No CSS found for {{.BRANCH}}"
          echo "💡 CI may not have run yet on this branch"
          exit 1
        fi

  css:
    desc: Ensure CSS is available (generate locally or download from CDN)
    cmds:
      - task: css-local
      - task: css-download

  css:watch:
    desc: Watch and recompile CSS on changes (development)
    deps: [install-tailwind]
    cmds:
      - |
        if [ ! -x {{.BIN_DIR}}/tailwindcss ]; then
          echo "❌ Tailwind CLI required for watch mode"
          exit 1
        fi
        {{.BIN_DIR}}/tailwindcss -i {{.CSS_INPUT}} -o {{.CSS_OUTPUT}} --watch

  build:
    desc: Build the application (includes CSS compilation)
    deps: [css]
    cmds:
      - go build -ldflags="{{.LDFLAGS}}" -o {{.BIN_DIR}}/odio-api .
      - echo "✓ Built {{.BIN_DIR}}/odio-api (version {{.VERSION}})"
    sources:
      - "**/*.go"
      - go.mod
      - go.sum
      - ui/templates/**/*.gohtml
      - ui/static/**
    generates:
      - "{{.BIN_DIR}}/odio-api"

  build:linux-amd64:
    desc: Cross-compile for Linux amd64
    deps: [css]
    env:
      GOOS: linux
      GOARCH: amd64
      CGO_ENABLED: "0"
    cmds:
      - mkdir -p dist
      - go build -ldflags="{{.LDFLAGS}}" -o dist/odio-api-linux-amd64 .
      - echo "✓ dist/odio-api-linux-amd64 ({{.VERSION}})"

  build:linux-armhf:
    desc: Cross-compile for Linux armhf (RPi B+/Zero/2/3 32-bit, ARMv6 hf = RPi OS armhf)
    deps: [css]
    env:
      GOOS: linux
      GOARCH: arm
      GOARM: "6"
      CGO_ENABLED: "0"
    cmds:
      - mkdir -p dist
      - go build -ldflags="{{.LDFLAGS}}" -o dist/odio-api-linux-armhf .
      - echo "✓ dist/odio-api-linux-armhf ({{.VERSION}})"

  build:linux-armv7hf:
    desc: Cross-compile for Linux armv7hf (RPi 2/3 32-bit, ARMv7 hard-float)
    deps: [css]
    env:
      GOOS: linux
      GOARCH: arm
      GOARM: "7"
      CGO_ENABLED: "0"
    cmds:
      - mkdir -p dist
      - go build -ldflags="{{.LDFLAGS}}" -o dist/odio-api-linux-armv7hf .
      - echo "✓ dist/odio-api-linux-armv7hf ({{.VERSION}})"

  build:linux-arm64:
    desc: Cross-compile for Linux arm64/aarch64 (RPi 3/4/5 64-bit)
    deps: [css]
    env:
      GOOS: linux
      GOARCH: arm64
      CGO_ENABLED: "0"
    cmds:
      - mkdir -p dist
      - go build -ldflags="{{.LDFLAGS}}" -o dist/odio-api-linux-arm64 .
      - echo "✓ dist/odio-api-linux-arm64 ({{.VERSION}})"

  build:all-arch:
    desc: Cross-compile for all supported architectures
    deps:
      - build:linux-amd64
      - build:linux-armhf
      - build:linux-armv7hf
      - build:linux-arm64

  package:deb:linux-amd64:
    desc: Build .deb package for amd64
    deps: [build:linux-amd64]
    env:
      VERSION: "{{.VERSION}}"
      NFPM_ARCH: amd64
      BINARY_PATH: dist/odio-api-linux-amd64
    cmds:
      - mkdir -p dist
      - |
        tmpfile=$(mktemp --suffix=.yaml)
        envsubst < nfpm.yaml > "$tmpfile"
        nfpm package --config "$tmpfile" --packager deb --target dist/
        rm -f "$tmpfile"
      - echo "✓ .deb amd64 ready in dist/"

  package:deb:linux-armhf:
    desc: Build .deb package for armhf (RPi OS ARMv6 hard-float)
    deps: [build:linux-armhf]
    env:
      VERSION: "{{.VERSION}}"
      NFPM_ARCH: armhf
      BINARY_PATH: dist/odio-api-linux-armhf
    cmds:
      - mkdir -p dist
      - |
        tmpfile=$(mktemp --suffix=.yaml)
        envsubst < nfpm.yaml > "$tmpfile"
        nfpm package --config "$tmpfile" --packager deb --target dist/
        rm -f "$tmpfile"
      - echo "✓ .deb armhf ready in dist/"

  package:deb:linux-armv7hf:
    desc: Build .deb package for armv7hf (RPi 2/3 32-bit)
    deps: [build:linux-armv7hf]
    env:
      VERSION: "{{.VERSION}}"
      NFPM_ARCH: armv7hf
      BINARY_PATH: dist/odio-api-linux-armv7hf
    cmds:
      - mkdir -p dist
      - |
        tmpfile=$(mktemp --suffix=.yaml)
        envsubst < nfpm.yaml > "$tmpfile"
        nfpm package --config "$tmpfile" --packager deb --target dist/
        rm -f "$tmpfile"
      - echo "✓ .deb armv7hf ready in dist/"

  package:deb:linux-arm64:
    desc: Build .deb package for arm64
    deps: [build:linux-arm64]
    env:
      VERSION: "{{.VERSION}}"
      NFPM_ARCH: arm64
      BINARY_PATH: dist/odio-api-linux-arm64
    cmds:
      - mkdir -p dist
      - |
        tmpfile=$(mktemp --suffix=.yaml)
        envsubst < nfpm.yaml > "$tmpfile"
        nfpm package --config "$tmpfile" --packager deb --target dist/
        rm -f "$tmpfile"
      - echo "✓ .deb arm64 ready in dist/"

  package:rpm:linux-amd64:
    desc: Build .rpm package for amd64
    deps: [build:linux-amd64]
    env:
      VERSION: "{{.VERSION}}"
      NFPM_ARCH: x86_64
      BINARY_PATH: dist/odio-api-linux-amd64
    cmds:
      - mkdir -p dist
      - |
        tmpfile=$(mktemp --suffix=.yaml)
        envsubst < nfpm.yaml > "$tmpfile"
        nfpm package --config "$tmpfile" --packager rpm --target dist/
        rm -f "$tmpfile"
      - echo "✓ .rpm x86_64 ready in dist/"

  package:rpm:linux-armv7hf:
    desc: Build .rpm package for armv7hf (RPi 2/3 32-bit)
    deps: [build:linux-armv7hf]
    env:
      VERSION: "{{.VERSION}}"
      NFPM_ARCH: armv7hl
      BINARY_PATH: dist/odio-api-linux-armv7hf
    cmds:
      - mkdir -p dist
      - |
        tmpfile=$(mktemp --suffix=.yaml)
        envsubst < nfpm.yaml > "$tmpfile"
        nfpm package --config "$tmpfile" --packager rpm --target dist/
        rm -f "$tmpfile"
      - echo "✓ .rpm armv7hl ready in dist/"

  package:rpm:linux-armhf:
    desc: Build .rpm package for armhf (ARMv6 hard-float)
    deps: [build:linux-armhf]
    env:
      VERSION: "{{.VERSION}}"
      NFPM_ARCH: armv6hl
      BINARY_PATH: dist/odio-api-linux-armhf
    cmds:
      - mkdir -p dist
      - |
        tmpfile=$(mktemp --suffix=.yaml)
        envsubst < nfpm.yaml > "$tmpfile"
        nfpm package --config "$tmpfile" --packager rpm --target dist/
        rm -f "$tmpfile"
      - echo "✓ .rpm armv6hl ready in dist/"

  package:rpm:linux-arm64:
    desc: Build .rpm package for arm64
    deps: [build:linux-arm64]
    env:
      VERSION: "{{.VERSION}}"
      NFPM_ARCH: aarch64
      BINARY_PATH: dist/odio-api-linux-arm64
    cmds:
      - mkdir -p dist
      - |
        tmpfile=$(mktemp --suffix=.yaml)
        envsubst < nfpm.yaml > "$tmpfile"
        nfpm package --config "$tmpfile" --packager rpm --target dist/
        rm -f "$tmpfile"
      - echo "✓ .rpm aarch64 ready in dist/"

  package:all:
    desc: Build all deb and rpm packages for all architectures
    deps:
      - package:deb:linux-amd64
      - package:deb:linux-armhf
      - package:deb:linux-armv7hf
      - package:deb:linux-arm64
      - package:rpm:linux-amd64
      - package:rpm:linux-armhf
      - package:rpm:linux-armv7hf
      - package:rpm:linux-arm64

  docker:build:
    desc: Build Docker image for local architecture
    cmds:
      - docker build --build-arg VERSION={{.VERSION}} -t odio-api:{{.VERSION}} .
      - echo "✓ Image odio-api:{{.VERSION}} built"

  docker:build:multi:
    desc: Build and push multi-arch Docker image (amd64, arm/v7, arm64)
    cmds:
      - |
        docker buildx build \
          --platform linux/amd64,linux/arm/v7,linux/arm64 \
          --build-arg VERSION={{.VERSION}} \
          -t ghcr.io/b0bbywan/go-odio-api:{{.VERSION}} \
          -t ghcr.io/b0bbywan/go-odio-api:latest \
          --push .

  test:
    desc: Run all tests
    deps: [css]
    cmds:
      - go test ./...

  test:verbose:
    desc: Run all tests with verbose output
    deps: [css]
    cmds:
      - go test -v ./...

  test:coverage:
    desc: Run tests with coverage report
    deps: [css]
    cmds:
      - go test -v -race -coverprofile=coverage.out -covermode=atomic ./...
      - go tool cover -func=coverage.out

  test:ui:
    desc: Run UI tests only
    deps: [css]
    cmds:
      - go test -v ./ui/...

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf {{.BIN_DIR}}/odio-api
      - rm -f {{.CSS_OUTPUT}}
      - echo "✓ Cleaned build artifacts"

  clean:all:
    desc: Clean all generated files (including Tailwind CLI)
    cmds:
      - rm -rf {{.BIN_DIR}}
      - rm -f {{.CSS_OUTPUT}}
      - echo "✓ Cleaned all generated files"

  dev:
    desc: Start development mode (CSS watch + manual server restart)
    deps: [css]
    cmds:
      - echo "Starting CSS watch mode..."
      - echo "Run 'go run .' in another terminal to start the server"
      - task: css:watch
